server:
  port: 8080
logging:
  file:
    name: logs/local/customer_management.log
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/customer_mgmt_db?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: customer_mgmt_app
    password: password
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  flyway:
    user: customer_mgmt_admin
    password: password
  profiles:
    active: local, clean
